server:
  port: 8001
spring:
  application:
    name: account
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
