server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/accounts/actuator/**
          filters:
            - RewritePath=/api/v1/accounts/(?<segment>.*), /$\{segment}
        - id: account
          uri: http://localhost:8001
          predicates:
            - Path=/api/*/accounts/**
