server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: http://localhost:8001
          predicates:
            - Path=/api/*/accounts/**
